### ISSUE TITLE
Make bookmarks stay on map after placed

### ISSUE THREAD

**Issue by rogerhnn** [w8r/Leaflet.Bookmarks#12]
I noticed that after I place the bookmark they hide. How I can make them stay on map?
Or better, if it uses a layer, can you tell me which layer, so I can toggle it on/off?
Thanks, awesome plugin

**Comment by w8r** [comment]
Can you please provide me with a jsfiddle to see the problem? I'm having difficulties reproducing that

Kind regards,
Alexander Milevski

**Comment by rogerhnn** [comment]
In your example, the actual bookmarks don't stay on map, they hide if I click on the map. Or if I click to create a new one, the other disappear. Its possible to make them all stay on the map, and not only appear if I click on them in the list?

**Comment by w8r** [comment]
You can redefine the `_onPopupClosed ` method so that it would store the markers elsewhere
```js
L.Control.Bookmarks.include({
  _onPopupClosed: function(evt) {
    someLayerGroup.addLayer(this._marker);
    this._marker = null;
  }
});
```

**Comment by rogerhnn** [comment]
Very nice! I added your plugin to my map, but it doesn't look as pretty as yours. And the bookmarks don't have the edit menu. Can you help me to set it up?

**Comment by w8r** [comment]
Did you add the `leaflet.bookmarks.css` file as well?

**Comment by rogerhnn** [comment]
Yeah, this is how it looks now: http://i.imgur.com/sULre48.png

What I have done so far: Added both `leaflet.bookmarks.css` and `leaflet.bookmarks.js` and the control `var control = new L.Control.Bookmarks().addTo(map);`

I need to manually add a way to add the markers?

**Comment by w8r** [comment]
It's hard to tell really. Any styling options could be overridden, but it will take some work. Did you check out the example? There's no additional styling as well

**Comment by rogerhnn** [comment]
I don't know why, but if I include your css on head or below body, I got an error `unexpected token` but I copied everything and pasted on my css and it works now.

**Comment by rogerhnn** [comment]
I use custom coordinates, its possible to change the coordinates shown by your plugin to match mine? I use x and y instead of lat, lng.
