### ISSUE TITLE
Remote storage

### ISSUE THREAD

**Issue by xsun125** [w8r/Leaflet.Bookmarks#15]
Sorry I'm really new to web developing. Could you explain more about remote storage with AJAX? 
1. In the example you said url: '/bookmarks/' + id I'm not quite sure what does that mean. (Isn't it supposed to point to the server handler first? eg. server.php)
2. In the 'data: value' part, should I use the variable 'value' straight away when using this plugin?
Thank you!

**Comment by w8r** [comment]
https://github.com/w8r/Leaflet.Bookmarks#custom-storageeg-ajax
