### ISSUE TITLE
multiple Add-bookmark-button div after window resize

### ISSUE THREAD

**Issue by luchsus** [w8r/Leaflet.Bookmarks#17]
In the bookmark popup template there are multiple div class="add-bookmark-button" elements after resizing the window. In my code and in your demo.
![image](https://user-images.githubusercontent.com/26462312/54338488-57fcb880-4632-11e9-8b46-4df5f3e9df15.png).
This leads to blurring text.

**Comment by faisal07m** [comment]
Any solution for this problem?
