### ISSUE TITLE
Plugin is broken with leaflet 1.9.3

### ISSUE THREAD

**Issue by B-e-n-G** [w8r/Leaflet.Bookmarks#30]
It seems the plugin is broken with the latest leaflet version 1.9.3 or one of the version before.
The exmaple runs with leaflet version 1.6.0.

**Comment by w8r** [comment]
I will check it out

**Comment by B-e-n-G** [comment]
To give more detailied informations... the this._close (for example in line 647) is undefined and the call _close() crashes.
It seems that this._popup is undefined as well (around this line).

**Comment by PedroVenancio** [comment]
Hi @w8r 
I have the same issue
```
Uncaught TypeError: this._close is not a function
    at NewClass._onSubmit (formpopup.js:284:12)
    at HTMLFormElement.handler (DomEvent.js:108:13)
```
﻿Is there anything we can do to overcome it? 

Thanks!

**Comment by PedroVenancio** [comment]
The origin of the issue seems to be this change:
https://github.com/Leaflet/Leaflet/pull/6962

**Comment by w8r** [comment]
fixed in 0.5.0

**Comment by PedroVenancio** [comment]
Hi @w8r 

Thank you very much for the update!! Do you plan to build the code again with version 0.5.0? dist folder was removed.

Thanks again!

**Comment by w8r** [comment]
Fixed in 0.5.1. You can get the built version from CDNs like [unpkg](https://unpkg.com/leaflet-bookmarks@0.5.1/dist/index.min.js)

**Comment by PedroVenancio** [comment]
Hi @w8r 

That's perfect now with v0.5.0: https://unpkg.com/browse/leaflet-bookmarks@0.5.0/dist/
However, it seems v0.5.1 does not generated the built version correctly: https://unpkg.com/browse/leaflet-bookmarks@0.5.1/dist/

Thank you very much for your work @w8r !

**Comment by w8r** [comment]
@PedroVenancio what do you mean it's not generated correctly? The files are there and they are linked properly in the `package.json`. Did you encounter some problem with `0.5.1`?

**Comment by PedroVenancio** [comment]
Hi @w8r 

I was expecting to see `Leaflet.Bookmarks.js` and `leaflet.bookmarks.css` in v0.5.1

![imagem](https://user-images.githubusercontent.com/1331581/219624018-156e9535-bcfd-49d7-8068-c2a11286c7ce.png)

just like in v0.5.0

![imagem](https://user-images.githubusercontent.com/1331581/219624723-360ac6eb-eaaf-4ba9-85e5-61eaa4757a6a.png)

**Comment by w8r** [comment]
ah, I renamed the files, it's reflected in `package.json`

 - `dist/L.Control.Bookmarks.js` &rarr; `dist/index.js`
 - `dist/L.Control.Bookmarks.minjs` &rarr; `dist/index.min.js`
- new `ESM` build is `dist/index.mjs`

**Comment by PedroVenancio** [comment]
Oh great! Thanks @w8r !!
