### ISSUE TITLE
Bookmark data for custom template

### ISSUE THREAD

**Issue by slongberry** [w8r/Leaflet.Bookmarks#7]
Really like the plugin, it has saved me a ton of time. I have come across one issue though.

We have the ability to customize the way the list of bookmarks appears through the bookmarkTemplate option. However, if I add a custom field to the bookmark, I don't see how to access that data to display it. 

I modified the _getBookmarkDataForTemplate function in the code to look more like the _getPopupContent function:

```javascript
  _getBookmarkDataForTemplate: function(bookmark) {
    if (this.options.getBookmarkDataForTemplate) {
      return this.options.getBookmarkDataForTemplate.call(this, bookmark);
    } else { 
    return {
      coords: this.formatCoords(bookmark.latlng),
      name: this.formatName(bookmark.name),
      zoom: bookmark.zoom,
      id: bookmark.id
      };
    }
  },
```

This allowed me to write me own custom getBookmarkDataForTemplate function and pass it to the bookmarks control as an option on creation. If there is another way that I should have accessed the data, please let me know.

**Comment by w8r** [comment]
@slongberry, you did just right, maybe you can adapt that into a pull request?

**Comment by slongberry** [comment]
I'll send you the PR on Monday morning.

Scott

**Comment by slongberry** [comment]
PR submitted. As it is my first PR submitted on Github, please let me know if I need to change anything / do anything differently!

**Comment by w8r** [comment]
@slongberry, thanks! merged, re-built, published
